name: Backend Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'shared/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'
      - 'shared/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          shared/package-lock.json
    
    - name: Install shared dependencies
      run: |
        cd shared
        npm ci
        npm run build
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
    
    - name: Run backend tests
      run: |
        cd backend
        npm test
      env:
        CI: true
    
    - name: Run backend tests with coverage
      run: |
        cd backend
        npm run test:coverage
      env:
        CI: true
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        file: ./backend/coverage/lcov.info
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false 